Backend6/Models/Forum.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace Backend6.Models
{
    public class Forum
    {
        public Guid Id { get; set; } = Guid.NewGuid();

        public Guid ForumCategoryId { get; set; }

        public ForumCategory ForumCategory { get; set; }

        [Required]
        [MaxLength(200)]
        public String Name { get; set; }

        public ICollection<ForumTopic> ForumTopics { get; set; }

        [Required]
        public String Description { get; set; }
    }
}

Backend6/Controllers/ForumCategoriesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Backend6.Data;
using Backend6.Models;
using Microsoft.AspNetCore.Authorization;
using Backend6.Models.ViewModels;

namespace Backend6.Controllers
{
    
    public class ForumCategoriesController : Controller
    {
        private readonly ApplicationDbContext _context;

        public ForumCategoriesController(ApplicationDbContext context)
        {
            _context = context;
        }

        // GET: ForumCategories
        public async Task<IActionResult> Index()
        {
            return View(await _context.ForumCategories
                .Include(x => x.Forums)
                .ThenInclude(x => x.ForumTopics)
                .ToListAsync());
        }

        [Authorize(Roles = ApplicationRoles.Administrators)]
        // GET: ForumCategories/Create
        public IActionResult Create()
        {
            return View(new ForumCategoryViewModel());
        }

        // POST: ForumCategories/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.

        [Authorize(Roles = ApplicationRoles.Administrators)]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(ForumCategoryViewModel model)
        {
            if (ModelState.IsValid)
            {
                var forumCategory = new ForumCategory
                {
                    Name = model.Name
                };

                _context.ForumCategories.Add(forumCategory);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(model);
        }

        // GET: ForumCategories/Edit/5

        [Authorize(Roles = ApplicationRoles.Administrators)]
        public async Task<IActionResult> Edit(Guid? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var forumCategory = await _context.ForumCategories.SingleOrDefaultAsync(m => m.Id == id);
            if (forumCategory == null)
            {
                return NotFound();
            }

            var model = new ForumCategoryViewModel
            {
                Name = forumCategory.Name
            };

            return View(model);
        }

        // POST: ForumCategories/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.

        [Authorize(Roles = ApplicationRoles.Administrators)]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(Guid id, ForumCategoryViewModel model)
        {
            if (id == null)
            {
                return NotFound();
            }

            var forumCategory = await _context.ForumCategories.SingleOrDefaultAsync(m => m.Id == id);
            if (forumCategory == null)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                forumCategory.Name = model.Name;
                await this._context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(model);
        }

        // GET: ForumCategories/Delete/5
        [Authorize(Roles = ApplicationRoles.Administrators)]
        public async Task<IActionResult> Delete(Guid? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var forumCategory = await _context.ForumCategories
                .SingleOrDefaultAsync(m => m.Id == id);
            if (forumCategory == null)
            {
                return NotFound();
            }

            return View(forumCategory);
        }

        // POST: ForumCategories/Delete/5
        [Authorize(Roles = ApplicationRoles.Administrators)]
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(Guid id)
        {
            var forumCategory = await _context.ForumCategories.SingleOrDefaultAsync(m => m.Id == id);
            _context.ForumCategories.Remove(forumCategory);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }
    }
}

Backend6/Controllers/ForumTopicsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Backend6.Data;
using Backend6.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Backend6.Services;
using Backend6.Models.ViewModels;

namespace Backend6.Controllers
{
    [Authorize]
    public class ForumTopicsController : Controller
    {
        private readonly ApplicationDbContext _context;
        private readonly UserManager<ApplicationUser> userManager1;
        private readonly IUserPermissionsService userPermissionsService;

        public ForumTopicsController(ApplicationDbContext context, UserManager<ApplicationUser> userManager, IUserPermissionsService userPermissions)
        {
            _context = context; 
            this.userManager1 = userManager;
            this.userPermissionsService = userPermissions;
        }

        // GET: ForumTopics
        public async Task<IActionResult> Index()
        {
            var applicationDbContext = _context.ForumTopics.Include(f => f.Creator).Include(f => f.Forum);
            return View(await applicationDbContext.ToListAsync());
        }

        [AllowAnonymous]
        // GET: ForumTopics/Details/5
        public async Task<IActionResult> Details(Guid? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var forumTopic = await _context.ForumTopics
                .Include(f => f.Creator)
                .Include(f => f.Forum)
                .Include(f => f.ForumMessages)
                .ThenInclude(f => f.Creator)
                .Include(f => f.ForumMessages)
                .ThenInclude(f => f.ForumMessageAttachments)
                .SingleOrDefaultAsync(m => m.Id == id);
            if (forumTopic == null)
            {
                return NotFound();
            }

            return View(forumTopic);
        }

        // GET: ForumTopics/Create
        public async Task<IActionResult> Create(Guid? forumId)
        {
            if (forumId == null)
            {
                return this.NotFound();
            }

            var forum = await this._context.Forums
               .SingleOrDefaultAsync(x => x.Id == forumId);

            if (forum == null)
            {
                return this.NotFound();
            }
            this.ViewBag.Forum = forum;
            return View(new ForumTopicViewModel());
        }

        // POST: ForumTopics/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(Guid? forumId, ForumTopicViewModel model)
        {
            if (forumId == null)
            {
                return NotFound();
            }

            var forum = await this._context.Forums
               .SingleOrDefaultAsync(x => x.Id == forumId);

            if (forum == null)
            {
                return NotFound();
            }

            var user = await this.userManager1.GetUserAsync(this.HttpContext.User);

            if (ModelState.IsValid)
            {
                var time = DateTime.UtcNow;
                var forumTopic = new ForumTopic
                {
                    ForumId = forum.Id,
                    CreatorId = user.Id,
                    Created = time,
                    Name = model.Name
                };

                _context.Add(forumTopic);
                await _context.SaveChangesAsync();
                return RedirectToAction("Details", "Forums", new { id = forum.Id });
            }

            ViewBag.Forum = forum;
            return View(model);
        }

        // GET: ForumTopics/Edit/5
        public async Task<IActionResult> Edit(Guid? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var forumTopic = await _context.ForumTopics
                .Include(m => m.Forum)
                .SingleOrDefaultAsync(m => m.Id == id);

            if (forumTopic == null || !this.userPermissionsService.CanEditForumTopic(forumTopic))
            {
                return NotFound();
            }

            var model = new ForumTopicViewModel
            {
                Name = forumTopic.Name
            };

            ViewBag.Forum = forumTopic.Forum;
            return View(model);
        }

        // POST: ForumTopics/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(Guid? id, ForumTopicViewModel model)
        {
            if (id == null)
            {
                return NotFound();
            }

            var forumTopic = await _context.ForumTopics
                .Include(m => m.Forum)
                .SingleOrDefaultAsync(m => m.Id == id);

            if (forumTopic == null || !this.userPermissionsService.CanEditForumTopic(forumTopic))
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                forumTopic.Name = model.Name;

                await this._context.SaveChangesAsync();
                return RedirectToAction("Details", "Forums", new { id = forumTopic.ForumId });
            }

            ViewBag.Forum = forumTopic.Forum;
            return View(model);
        }

        // GET: ForumTopics/Delete/5
        public async Task<IActionResult> Delete(Guid? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var forumTopic = await _context.ForumTopics
                .Include(f => f.Creator)
                .Include(f => f.Forum)
                .SingleOrDefaultAsync(m => m.Id == id);
            if (forumTopic == null || !this.userPermissionsService.CanEditForumTopic(forumTopic))
            {
                return NotFound();
            }
            ViewBag.Forum = forumTopic.Forum;
            return View(forumTopic);
        }

        // POST: ForumTopics/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(Guid id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var forumTopic = await _context.ForumTopics
                .Include(f => f.Creator)
                .Include(f => f.Forum)
                .SingleOrDefaultAsync(m => m.Id == id);
            if (forumTopic == null || !this.userPermissionsService.CanEditForumTopic(forumTopic))
            {
                return NotFound();
            }
            ViewBag.Forum = forumTopic.Forum;
            _context.ForumTopics.Remove(forumTopic);
            await _context.SaveChangesAsync();
            return RedirectToAction("Details", "Forums", new { id = forumTopic.ForumId });
        }
    }
}

Backend6/Views/Forums/Create.cshtml
@model Backend6.Models.ViewModels.ForumCreateViewModel

@{
    ViewData["Title"] = "Create";
}

<h2>Create</h2>

<h4>Forum</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create" asp-route-categoryId="@ViewBag.Category.Id">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Description" class="control-label"></label>
                <input asp-for="Description" class="form-control" />
                <span asp-validation-for="Description" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index" asp-controller="ForumCategories">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Backend6/Views/Forums/Delete.cshtml
@model Backend6.Models.Forum

@{
    ViewData["Title"] = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Forum</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Name)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Description)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Description)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Delete" class="btn btn-default" /> |
        <a asp-controller="ForumCategories" asp-action="Index" asp-route-categoryId="@ViewBag.Forum.ForumCategoryId">Back to List</a>
    </form>
</div>

Backend6/Views/Forums/Details.cshtml
@model Backend6.Models.Forum

@{
    ViewData["Title"] = "Details";
}

<h2>@Model.Name</h2>
<p>@Model.Description</p>

@if (User.Identity.IsAuthenticated)
{
    <p>
        <a asp-action="Create" asp-controller="ForumTopics" asp-route-forumId="@ViewBag.Forum.Id">Create new topic</a>
    </p>
}

<div class="panel panel-default">
    <table class="table table-striped">
        <tbody>
            @foreach (var topic in Model.ForumTopics.OrderByDescending(x => x.Created))
            {
                <tr>
                    <td>
                        <a asp-controller="ForumTopics" asp-action="Details" asp-route-id="@topic.Id" style="font-size: 1.3em">@topic.Name</a><br />
                        @topic.Creator.UserName, @topic.Created
                    </td>
                    @if (topic.ForumMessages.Count() > 0)
                    {
                        <td style="width: 100px">
                            @topic.ForumMessages.Count replies
                        </td>
                        <td style="width: 220px">
                            @topic.ForumMessages.OrderByDescending(x => x.Created).First().Creator.UserName<br />
                            @topic.ForumMessages.OrderByDescending(x => x.Created).First().Modified
                        </td>
                    }
                    else
                    {
                        <td style="width: 100px">
                            0 replies
                        </td>
                        <td style="width: 220px">
                            @topic.Creator.UserName<br />
                            @topic.Created
                        </td>
                    }
                </tr>
            }
        </tbody>
    </table>
</div>

Backend6/Views/Forums/Edit.cshtml
@model Backend6.Models.ViewModels.ForumCreateViewModel

@{
    ViewData["Title"] = "Edit";
}

<h2>Edit</h2>

<h4>Forum</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Description" class="control-label"></label>
                <input asp-for="Description" class="form-control" />
                <span asp-validation-for="Description" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-controller="ForumCategories" asp-action="Index" asp-route-categoryId="@ViewBag.Forum.ForumCategoryId">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Backend6/Views/Forums/Index.cshtml
@model IEnumerable<Backend6.Models.Forum>

@{
    ViewData["Title"] = "Index";
}

<h2>Index</h2>

<p>
    <a asp-action="Create">Create New</a>
</p>
<table class="table">
    <thead>
        <tr>
                <th>
                    @Html.DisplayNameFor(model => model.Name)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Description)
                </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Name)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Description)
            </td>
            <td>
                <a asp-action="Edit" asp-route-id="@item.Id">Edit</a> |
                <a asp-action="Details" asp-route-id="@item.Id">Details</a> |
                <a asp-action="Delete" asp-route-id="@item.Id">Delete</a>
            </td>
        </tr>
}
    </tbody>
</table>